### ISSUE TITLE
Create files in the original file's directory?

### ISSUE THREAD

**Issue by ppentchev** [zchunk/zchunk#29]
Hi,

"This is more of a comment than a question..." :) ...or rather it is more of a question than a bug report. Apologies if this has been asked and answered before, but I couldn't find it in your blog posts or in the zchunk source.

So... is there a reason why the command-line utilities, most of all zck and unzck, will generate a file in the current working directory instead of in the directory where the original file resides? I know this is on purpose, I have seen the basename() invocations in the source. The thing is, it does strike me as a bit odd, since my first assumption was that zck/unzck operate in a similar manner to gzip/gunzip, bzip2/bunzip2, xz/unxz, etc - and all of these, when invoked on /tmp/file.txt, will produce a /tmp/file.txt.ext (or vice versa).

OK, well, so the argument could be made that all of the tools I listed are "destructive" - they remove the original file and leave only the compressed/decompressed one. If you say that zck/unzck is not really similar to those, then, okay, of course I'll accept your author/maintainer's position on this :)

G'luck,
Peter

**Comment by jdieter** [comment]
That's a fair question.  I did this because it seemed logical to me, since zck and unzck are intentionally non-destructive.

If this was a brand-new project, I'd probably would work in the directory where the original file resides, but I would really hesitate to make a massive userspace change like this now, when we've been at release 1.0+ for over a year.  I've made an ABI/API stability promise, and while this wouldn't violate the letter of that promise, this would probably violate its spirit.

What do you think?

**Comment by ppentchev** [comment]
Thanks for your answer! It's reasonable, and yes, I did consider the "maybe it's too late to change it now" angle before posting.

This was indeed more of a question and I felt a bit guilty posting it in an issue tracker. Thanks for your thoughts and keep up the great work! :)

G'luck,
Peter
