### ISSUE TITLE
Multiple tests fail with zstd 1.5

### ISSUE THREAD

**Issue by ismail** [zchunk/zchunk#41]
This is on openSUSE Tumbleweed x86_64 with zstd 1.5 and zchunk 1.1.11

```
--- command ---
07:32:49 /home/abuild/rpmbuild/BUILD/zchunk-1.1.11/x86_64-suse-linux/test/shacheck src/zck LICENSE.nodict.fodt.zck eff3098803ba80f0c446d49f48188f89167d7f29cdc8a98c19f0ecfb4e2ee3c9 -o LICENSE.nodict.fodt.zck /home/abuild/rpmbuild/BUILD/zchunk-1.1.11/test/files/LICENSE.fodt
--- stdout ---
LICENSE.nodict.fodt.zck:
Calculated checksum: (SHA-256)3d2fa50ede0d2d70c9683e5a175819f2cb597bc4b2a6fe3cea5f2b8b2f78d2cc
Expected checksum: (SHA-256)eff3098803ba80f0c446d49f48188f89167d7f29cdc8a98c19f0ecfb4e2ee3c9
Checksums don't match!
-------

24/26 compress auto-chunked file - dict      FAIL           0.05s (exit status 1)

--- command ---
07:32:49 /home/abuild/rpmbuild/BUILD/zchunk-1.1.11/x86_64-suse-linux/test/shacheck src/zck LICENSE.dict.fodt.zck b86795ca14eb04b382d1c7f94501aa5d1a2ddb05a5351c0235d00edb954e9b66 -D /home/abuild/rpmbuild/BUILD/zchunk-1.1.11/test/files/LICENSE.dict -o LICENSE.dict.fodt.zck /home/abuild/rpmbuild/BUILD/zchunk-1.1.11/test/files/LICENSE.fodt
--- stdout ---
LICENSE.dict.fodt.zck:
Calculated checksum: (SHA-256)a939da7db34d3e1cbb9970c092a8902a3dc3fc2dda8469c24dfda4aebbd6e164
Expected checksum: (SHA-256)b86795ca14eb04b382d1c7f94501aa5d1a2ddb05a5351c0235d00edb954e9b66
Checksums don't match!
-------

25/26 compress manual file - no dict         FAIL           0.12s (exit status 1)

--- command ---
07:32:49 /home/abuild/rpmbuild/BUILD/zchunk-1.1.11/x86_64-suse-linux/test/shacheck src/zck LICENSE.manual.nodict.fodt.zck c46929367cd3d05daaca3b44657726791b428fb2198f5e7e5367b5cc781307aa -m -s <text: -o LICENSE.manual.nodict.fodt.zck /home/abuild/rpmbuild/BUILD/zchunk-1.1.11/test/files/LICENSE.fodt
--- stdout ---
LICENSE.manual.nodict.fodt.zck:
Calculated checksum: (SHA-256)c715ef49e4582ef155e185eb665551fe065bafb21c07a69cc71d90075da034ff
Expected checksum: (SHA-256)c46929367cd3d05daaca3b44657726791b428fb2198f5e7e5367b5cc781307aa
Checksums don't match!
-------

26/26 compress manual file - dict            FAIL           0.57s (exit status 1)

--- command ---
07:32:49 /home/abuild/rpmbuild/BUILD/zchunk-1.1.11/x86_64-suse-linux/test/shacheck src/zck LICENSE.manual.dict.fodt.zck 5fc2449aeb51f6a898529fa4d53b04de6df6a352826f819dc2b39b153ddaa788 -D /home/abuild/rpmbuild/BUILD/zchunk-1.1.11/test/files/LICENSE.dict -m -s <text: -o LICENSE.manual.dict.fodt.zck /home/abuild/rpmbuild/BUILD/zchunk-1.1.11/test/files/LICENSE.fodt
--- stdout ---
LICENSE.manual.dict.fodt.zck:
Calculated checksum: (SHA-256)acda73e0092dd33de24e51db09f8611dd7330837c393cabdaaee7ea0f79e6309
Expected checksum: (SHA-256)5fc2449aeb51f6a898529fa4d53b04de6df6a352826f819dc2b39b153ddaa788
Checksums don't match!
```

**Comment by bmwiedemann** [comment]
I guess, what the tests should be testing is: can the compressed file be uncompressed to the original again? Is it below a certain size? Does compression+decompression complete in reasonable time? (can vary in VMs and containers from scheduling)

**Comment by jdieter** [comment]
This should be fixed in 0a6d5688a491324d971fc13b567c1076c48ac9ba.  I've pushed out 1.1.12 which contains the fix.  Please reopen if this is not the case.

**Comment by ismail** [comment]
Thanks, but now the tests fail on i586, ppc, ppc64le and s390x. Updating checksums for each zstd release doesn't sound right either but admittedly, I don't know the use case of zchunk.

Anyhow, please see https://build.opensuse.org/project/show/home:namtrac:branches:Archiving for the current failures.

**Comment by jdieter** [comment]
Well, that sucks.  I agree that using checksums is less than ideal, but the purpose of the test is twofold:
1. Verify that the created file is valid (an easy alternate method would be to decompress the compressed file, but this would leave us vulnerable to possible non-backwards compatible code changes that affect both compression and decompression.  I probably need to write a separate simple zchunk decompressor to verify these files.)
2. Flag changes to zstd compression.  The problem is that any changes to zstd that change the generated checksums will also break the ability of zchunk to match checksums on older versions of the zchunk file.

The failures are currently highlighting problem 2, and, being fair, there's not much we can do about it.  But zstd is supposed to [guarantee deterministic results](https://github.com/facebook/zstd/issues/2079#issuecomment-612195299) for a given version of zstd with the same compression options, even across different architectures.  If we're seeing different compression results in i586 and x86_64, this is a zstd bug that we need fixed (otherwise zchunk files generated on one architecture will be different than zchunk files generated on a second).

I'm reopening this issue because of the problems for the other arches.  Unless someone has a better idea, I will probably write a simple pure python zchunk decompressor and use it for the tests, and will open an issue with zstd to make sure the compression is deterministic across arches.

**Comment by jdieter** [comment]
Some followup on this.  I've checked out the command line results for zstd compression for x86_64 vs ppc64le and they're identical, so we must be doing something strange when we're doing the compression.  Interestingly, it's only the first chunk that's inconsistent.

**Comment by bmwiedemann** [comment]
Maybe related: In the link, there is a discussion on how libzstd is single-threaded by default and `zstd` CLI is multi-threaded by default (even with 1 thread) and those return different results.

**Comment by jdieter** [comment]
Ok, this has been a bit of a roller coaster, but I've managed to get consistent results across different arches in zchunk-1.1.14 by forcing the compression strategy.  I've managed to successfully build zchunk on all the Fedora architectures, so I think this is really fixed this time.  Please re-open this ticket if I'm wrong (again).

**Comment by ismail** [comment]
Happy to report that, it works everywhere. Thank you! :)
