### ISSUE TITLE
Plans for new release?

### ISSUE THREAD

**Issue by martinetd** [zchunk/zchunk#53]
Hi,

I'm a selfish swupdate user interested in using the new APIs @sbabic pushed recently, but it'd be appreciable to have a new release cut out in order to package a proper version (I'll then push the package to alpine's testing repo if you don't mind)

Do you have any plan to cut a 1.2.0 release soon?

Thanks!

**Comment by jdieter** [comment]
I would really like to either see `zckdl` grow support for handling an uncompressed source zchunk file or see a POC of other code that can handle the same before pushing out 1.2.0.

**Comment by wolfv** [comment]
I agree, it would be very nice to get a release with the fixes for Windows so that we can propagate this into the package on conda-forge and use it from our application.

**Comment by wolfv** [comment]
ping @jdieter would you be able to give an estimate? Otherwise we would need to ship a really large patch which wouldn't be nice (for a release through this "feedstock" on conda-forge: https://github.com/conda-forge/zchunk-feedstock

**Comment by jdieter** [comment]
Hey @wolfv and @martinetd, apologies for the delay on this.  I am working on getting the code for handling an uncompressed source zchunk file into `zckdl`.  The problem is that new functions have been added to `zck.h` and, once I make a release, the ABI is fixed, so I want to make sure the changes are suitable before releasing 1.2.0.  See PR #69 for my current WIP.

**Comment by jdieter** [comment]
So, once again apologies on the delay here.  It turns out that #69 is going to be harder than I thought, so I've gone ahead and pushed out version 1.2.0.

**Comment by wolfv** [comment]
Awesome!
